// writes the NEAR OHM brand-kit scenes into _studio/src (then: node _studio/render.js)
const fs = require('fs'), path = require('path'); const S = path.join(__dirname, 'src');
const X = process.env.X_HANDLE || '@NearOHM', DOMAIN = process.env.DOMAIN || '';
const foot = `<div class="abs mono" style="left:130px;right:130px;bottom:80px;display:flex;justify-content:space-between;font-size:26px;color:#4b4f4b"><span style="display:flex;align-items:center;gap:20px;color:#000"><span class="mk" style="width:44px;height:44px;font-size:24px">N</span>NEAR OHM · $NOHM</span><span>${DOMAIN ? DOMAIN + ' · ' : ''}${X} · NEAR</span></div>`;
const page = (body, css = '') => `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2400px;height:1350px}.pad{position:absolute;inset:110px 130px}.kick{font-family:'IBM Plex Mono';font-size:24px;letter-spacing:.3em;text-transform:uppercase;color:#4b4f4b}${css}</style><body><div class="grid"></div>${body}${foot}`;
const w = (f, s) => fs.writeFileSync(path.join(S, f), s);

w('nohm-pfp.html', `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2000px;height:2000px;background:#00ec97;display:grid;place-items:center}</style><body><div class="u" style="font-size:1150px;color:#000;transform:translateY(-40px)">N</div><div class="abs mono" style="bottom:120px;left:0;right:0;text-align:center;font-size:54px;color:#000">near ohm · (3,3)</div>`);
w('nohm-banner.html', `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:3000px;height:1000px}</style><body><div class="grid"></div><div class="u abs" style="left:150px;top:150px;font-size:180px">The reserve<br>currency<br>of <span class="gr">NEAR.</span></div><div class="abs mono" style="left:158px;bottom:130px;font-size:40px;color:#4b4f4b">near ohm · $nohm · stake · bond · (3,3)${DOMAIN ? ' · ' + DOMAIN : ''}</div><div class="abs mk" style="right:180px;top:200px;width:560px;height:560px;font-size:400px;box-shadow:30px 30px 0 #000">N</div>`);
w('nohm-keyart.html', page(`<div class="pad"><div class="kick">OHM (3,3) · on NEAR</div><div class="u" style="font-size:150px;margin-top:60px">The reserve<br>currency<br>of <span class="gr">NEAR.</span></div></div><div class="box ink sh abs" style="right:130px;top:300px;width:780px;height:620px;padding:50px"><div class="mono" style="font-size:22px;color:#9a9a9a">current apy</div><div class="u" style="font-size:150px;color:#00ec97;margin-top:24px;letter-spacing:-.04em">12,000%</div><div class="mono" style="font-size:22px;color:#bbb;margin-top:30px;letter-spacing:.14em">rebase every 8 hours</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:30px;margin-top:70px"><div><div class="mono" style="font-size:20px;color:#9a9a9a">bond discount</div><div class="u" style="font-size:64px;margin-top:10px">6.5%</div></div><div><div class="mono" style="font-size:20px;color:#9a9a9a">treasury</div><div class="u" style="font-size:64px;margin-top:10px">real Ⓝ</div></div></div></div>`));
const moves = [['01', 'Bond NEAR', 'Send NEAR to the treasury, receive NOHM below market. 6.5% off over five days, 12% off over fourteen.'], ['02', 'Stake NOHM', 'Staked NOHM becomes sNOHM. Every eight-hour epoch the index rises and your balance rises with it.'], ['03', '(3,3)', 'When everyone stakes, the index compounds for everyone. Selling is the only move that helps no one.']];
w('nohm-moves.html', page(`<div class="pad"><div class="kick">how it works</div><div class="u" style="font-size:112px;margin-top:40px">Three moves. <span class="gr">One is right.</span></div><div class="g">${moves.map((m) => `<div class="box s"><div class="u n">${m[0]}</div><h2 class="u">${m[1]}</h2><p>${m[2]}</p></div>`).join('')}</div></div>`, `.g{display:grid;grid-template-columns:repeat(3,1fr);gap:0;margin-top:90px;border:3px solid #000}.s{border:none;border-right:3px solid #000;padding:54px 48px;height:560px}.s:last-child{border-right:none}.n{font-size:120px;color:#00ec97;-webkit-text-stroke:3px #000}.s h2{font-size:48px;letter-spacing:-.02em;margin:40px 0 26px;font-weight:700}.s p{font-size:29px;line-height:1.55;color:#4b4f4b}`));
w('nohm-treasury.html', page(`<div class="pad"><div class="kick">the treasury</div><div class="u" style="font-size:112px;margin-top:40px">Real NEAR.<br><span class="gr">Read it on-chain.</span></div><div style="display:grid;grid-template-columns:1.1fr .9fr;gap:60px;margin-top:80px;align-items:start"><p style="font-size:36px;line-height:1.55;color:#4b4f4b;max-width:1100px">Every deposit is a plain NEAR transfer to the treasury account, verified against NEAR RPC before a single yoctoNEAR is credited. The balance on the site is read from the chain, not from a spreadsheet. Withdrawals are paid from a cold wallet. No hot key on the server.</p><div class="box sh" style="padding:0">${[['epoch', '8 hours'], ['apy', '12,000%'], ['bonds', '6.5% · 12%'], ['vesting', '5 · 14 days'], ['supply', '1,000,000,000'], ['chain', 'NEAR mainnet']].map((r) => `<div style="display:flex;justify-content:space-between;padding:26px 36px;border-bottom:3px solid #000;font-size:30px"><span class="mono" style="font-size:22px;color:#4b4f4b;align-self:center">${r[0]}</span><b style="font-family:'IBM Plex Mono';font-weight:600">${r[1]}</b></div>`).join('')}</div></div></div>`));
const cells = [['', 'you stake', 'you bond', 'you sell'], ['they stake', '(3,3)', '(1,3)', '(−1,1)'], ['they bond', '(3,1)', '(1,1)', '(−1,1)'], ['they sell', '(1,−1)', '(1,−1)', '(−3,−3)']];
w('nohm-33.html', page(`<div class="pad"><div class="kick">game theory</div><div class="u" style="font-size:112px;margin-top:40px">Both stake. <span class="gr">Everybody wins.</span></div><div class="m">${cells.map((row, i) => row.map((c, j) => `<div class="c ${i === 0 || j === 0 ? 'h' : ''} ${c === '(3,3)' ? 'win' : ''} ${c === '(−3,−3)' ? 'lose' : ''}">${c}</div>`).join('')).join('')}</div></div>`, `.m{display:grid;grid-template-columns:300px repeat(3,1fr);margin-top:80px;border:3px solid #000;width:1500px}.c{padding:40px;border-right:3px solid #000;border-bottom:3px solid #000;font-family:'Unbounded';font-weight:700;font-size:52px;text-align:center;background:#fff}.c:nth-child(4n){border-right:none}.c:nth-last-child(-n+4){border-bottom:none}.h{font-family:'IBM Plex Mono';font-size:22px;letter-spacing:.2em;text-transform:uppercase;color:#4b4f4b;background:#f4f5f3;display:grid;place-items:center;font-weight:500}.win{background:#00ec97}.lose{background:#000;color:#ff7966}`));
w('nohm-index.html', page(`<div class="pad"><div class="kick">the index</div><div class="u" style="font-size:112px;margin-top:40px">Nothing to claim.<br><span class="gr">It just goes up.</span></div><div class="box ink sh" style="margin-top:80px;padding:60px 70px;display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:center"><div><div class="mono" style="font-size:22px;color:#9a9a9a">index · epoch 1,095</div><div class="u" style="font-size:150px;color:#00ec97;margin-top:20px;letter-spacing:-.04em">121.0</div><div class="mono" style="font-size:22px;color:#bbb;margin-top:20px;letter-spacing:.14em">1 snohm at launch → 121 nohm after one year</div></div><div style="font-family:'IBM Plex Mono';font-size:30px;line-height:1.9;color:#fff"><div>r = 121<sup>1/1095.75</sup> − 1</div><div>r ≈ <span style="color:#00ec97">0.4386%</span> per epoch</div><div>index ← index × (1 + r)</div><div>sNOHM = shares × index</div></div></div></div>`));
let r = fs.readFileSync(path.join(__dirname, 'render.js'), 'utf8'); fs.writeFileSync(path.join(__dirname, 'render.js'), r);
console.log('nohm kit scenes written (' + X + (DOMAIN ? ' · ' + DOMAIN : '') + ')');
